CREATE TABLE search_history (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                origin_location_code VARCHAR(255),
                                destination_location_code VARCHAR(255),
                                departure_date VARCHAR(255),
                                adults INT NOT NULL,
                                search_timestamp TIMESTAMP
);