CREATE TABLE favorite_flight (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 origin VARCHAR(255),
                                 destination VARCHAR(255),
                                 departure_date VARCHAR(255),
                                 arrival_date VARCHAR(255),
                                 carrier VARCHAR(255),
                                 price NUMERIC(19, 2),
                                 added_at TIMESTAMP
);